/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matchpostpone;

import java.awt.event.*;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PC
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HiomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        PostponeB = new javax.swing.JButton();
        button_Schedule = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("       ProLeague Scheduler");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 600, 89));

        PostponeB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PostponeB.setForeground(new java.awt.Color(153, 0, 51));
        PostponeB.setText("2- View Schedule after postpone");
        PostponeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostponeBActionPerformed(evt);
            }
        });
        getContentPane().add(PostponeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 290, 70));

        button_Schedule.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_Schedule.setForeground(new java.awt.Color(102, 0, 51));
        button_Schedule.setText("1- View Schedule ");
        button_Schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ScheduleActionPerformed(evt);
            }
        });
        getContentPane().add(button_Schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 290, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matchpostpone/WhatsApp Image 2025-07-10 at 12.22.33_98570c14.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 920, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleButtonActionPerformed

    }//GEN-LAST:event_scheduleButtonActionPerformed

    private void postponedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postponedButtonActionPerformed

    }//GEN-LAST:event_postponedButtonActionPerformed

    private void PostponeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostponeBActionPerformed
        PostponedFrame postponed;
        try {
            postponed = new PostponedFrame();
            postponed.setVisible(true);

        } 
        catch (IOException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ParseException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PostponeBActionPerformed

    private void button_ScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ScheduleActionPerformed
        // TODO add your handling code here:
        SchedulerFrame schedule = new SchedulerFrame();
        schedule.setVisible(true);

    }//GEN-LAST:event_button_ScheduleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PostponeB;
    private javax.swing.JButton button_Schedule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
